---
title: "Lab 01 - Hello R!"
author: "Ashton Hunter"
date: "01-31-2022"
output: html_document
---

```{r load-libraries, include=FALSE}
# Load required libraries
library(tidyverse) 
library(datasauRus)
```

# Exercise 1

```{r ex-1}
table(datasaurus_dozen$dataset)
datasaurus_dozen %>%
  count(dataset)
dim(datasaurus_dozen)
names(datasaurus_dozen)
```

According to the help file there are 13 rows and 2 columns. The variables included in data drame are: away, bullseye, circle, dino, h_lines, high_lines, slant_down, slant_up, star, v_lines, wide_lines, x_shape. 


# Exercise 2

```{r ex-2}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r}
dino_data %>%
  summarize(r = cor(x, y))
```


# Exercise 3

```{r ex-3}
# your code for Exercise 3 goes here
```

YOUR RESPONSE FOR EXERCISE 3 GOES HERE.


# Exercise 4

```{r ex-4}
# your code for Exercise 4 goes here
```

YOUR RESPONSE FOR EXERCISE 4 GOES HERE.

# Exercise 5

```{r ex-5}
# your code for Exercise 5 goes here
```

YOUR RESPONSE FOR EXERCISE 5 GOES HERE.
